"""report_model_added

Revision ID: 98ce9d26d3e8
Revises: 8489b5758f6b
Create Date: 2026-07-20 13:51:42.978949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ce9d26d3e8'
down_revision: Union[str, Sequence[str], None] = '8489b5758f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('POLICE', 'FLOODING', 'ROAD_DANGER', 'TRAFFIC_JAM', 'MISSING_SIGN', 'CAR_ACCIDENT', 'CONSTRUCTION', 'SPEED_CAMERA', name='report_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    sa.Enum(name='report_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
